sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "8"

matrix:
  fast_finish: true

before_install:
  - npm install chalk
  - npm install each-async
  - npm install indent-string
  - npm install npm@5 -g
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install

script:
- npm run ci:travis
  
notifications:
  slack: wigo4it:GdebqlKcoyti7ff14Vnt1IHD