sudo: true
dist: xenial
language: node_js

addons:
  chrome: stable

node_js:
  - "8"

before_install:
  - npm install chalk
  - npm install each-async
  - npm install indent-string
  - npm install npm@5 -g
  - npm prune
  - npm update

install:
  - npm install
  
notifications:
  slack: wigo4it:GdebqlKcoyti7ff14Vnt1IHD