/**
 * NPS op RaadpleegIngeschrevenPersoonNAW
 * NPS op RaadpleegIngeschrevenPersoonNAW (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BrpAdresbuitenlandLandcode } from './brpAdresbuitenlandLandcode';


/**
 * 
 */
export interface BrpAdresbuitenland {
    /**
     * Gets or Sets Landcode
     */
    landcode?: BrpAdresbuitenlandLandcode;
}
