/**
 * NPS op RaadpleegIngeschrevenPersoonNAW
 * NPS op RaadpleegIngeschrevenPersoonNAW (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface BrpAdresbuitenlandLandcode {
    /**
     * Gets or Sets AdresBuiteland3
     */
    adresBuiteland3?: string;
    /**
     * Gets or Sets AdresBuiteland1
     */
    adresBuiteland1?: string;
    /**
     * Gets or Sets AdresBuiteland2
     */
    adresBuiteland2?: string;
    /**
     * Gets or Sets Landnaam
     */
    landnaam?: string;
}
