/**
 * NPS op RaadpleegIngeschrevenPersoonNAW
 * NPS op RaadpleegIngeschrevenPersoonNAW (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BrpAdresbuitenland } from './brpAdresbuitenland';
import { BrpIngeschrevenPersoonOverlijden } from './brpIngeschrevenPersoonOverlijden';
import { BrpIngeschrevenPersoonVerblijfstitel } from './brpIngeschrevenPersoonVerblijfstitel';
import { BrpPersoon } from './brpPersoon';
import { BrpVerblijfsadres } from './brpVerblijfsadres';


/**
 * 
 */
export interface BrpIngeschrevenPersoon {
    /**
     * Gets or Sets VoorletterAanschrijving
     */
    voorletterAanschrijving?: string;
    /**
     * Gets or Sets Voornamen
     */
    voornamen?: string;
    /**
     * Gets or Sets VoorvoegselGeslachtnaam
     */
    voorvoegselGeslachtnaam?: string;
    /**
     * Gets or Sets Geslachtsnaam
     */
    geslachtsnaam?: string;
    /**
     * Gets or Sets Geslachtsaanduiding
     */
    geslachtsaanduiding?: string;
    /**
     * Gets or Sets Aanschrijfwijze
     */
    aanschrijfwijze?: string;
    /**
     * Gets or Sets GeboorteDatum
     */
    geboorteDatum?: Date;
    /**
     * Gets or Sets Verblijfsadres
     */
    verblijfsadres?: BrpVerblijfsadres;
    /**
     * Gets or Sets Adresbuitenland
     */
    adresbuitenland?: BrpAdresbuitenland;
    /**
     * Gets or Sets Burgerservicenummer
     */
    burgerservicenummer?: number;
    /**
     * Gets or Sets AanduidingNaamgebruik
     */
    aanduidingNaamgebruik?: string;
    /**
     * Gets or Sets AanhefAanschrijving
     */
    aanhefAanschrijving?: string;
    /**
     * Gets or Sets VoornamenAanschrijving
     */
    voornamenAanschrijving?: string;
    /**
     * Gets or Sets GeslachtsnaamAanschrijving
     */
    geslachtsnaamAanschrijving?: string;
    /**
     * Gets or Sets AdelijkeTitelOfPredikant
     */
    adelijkeTitelOfPredikant?: string;
    /**
     * Gets or Sets Geboorteplaats
     */
    geboorteplaats?: string;
    /**
     * Gets or Sets Geboorteland
     */
    geboorteland?: string;
    /**
     * Gets or Sets Ouder
     */
    ouder?: Array<BrpPersoon>;
    /**
     * Gets or Sets Partner
     */
    partner?: Array<BrpPersoon>;
    /**
     * Gets or Sets Overlijden
     */
    overlijden?: BrpIngeschrevenPersoonOverlijden;
    /**
     * Gets or Sets Telefoonnummer
     */
    telefoonnummer?: string;
    /**
     * Gets or Sets Faxnummer
     */
    faxnummer?: string;
    /**
     * Gets or Sets Emailadres
     */
    emailadres?: string;
    /**
     * Gets or Sets Verblijfstitel
     */
    verblijfstitel?: BrpIngeschrevenPersoonVerblijfstitel;
}
