/**
 * NPS op RaadpleegIngeschrevenPersoonNAW
 * NPS op RaadpleegIngeschrevenPersoonNAW (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface BrpIngeschrevenPersoonVerblijfstitel {
    /**
     * Gets or Sets Omschrijving
     */
    omschrijving?: string;
    /**
     * Gets or Sets Code
     */
    code?: string;
    /**
     * Gets or Sets BeginDatumGeldigheid
     */
    beginDatumGeldigheid?: Date;
    /**
     * Gets or Sets EindDatumGeldigheid
     */
    eindDatumGeldigheid?: Date;
}
