/**
 * NPS op RaadpleegIngeschrevenPersoonNAW
 * NPS op RaadpleegIngeschrevenPersoonNAW (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: 1.0.0
 * Contact:
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BrpAdresbuitenland } from './brpAdresbuitenland';
import { BrpPersoonPeriodeGeldigheid } from './brpPersoonPeriodeGeldigheid';
import { BrpVerblijfsadres } from './brpVerblijfsadres';


/**
 *
 */
export interface BrpPersoon {
    /**
     * Gets or Sets PeriodeGeldigheid
     */
    periodeGeldigheid?: BrpPersoonPeriodeGeldigheid;
    /**
     * Gets or Sets VoorlettersAanschrijving
     */
    voorlettersAanschrijving?: string;
    /**
     * Gets or Sets Voornamen
     */
    voornamen?: string;
    /**
     * Gets or Sets VoorvoegselGeslachtsnaam
     */
    voorvoegselGeslachtsnaam?: string;
    /**
     * Gets or Sets Geslachtsnaam
     */
    geslachtsnaam?: string;
    /**
     * Gets or Sets Geslachtsaanduiding
     */
    geslachtsaanduiding?: string;
    /**
     * Gets or Sets Aanschrijfwijze
     */
    aanschrijfwijze?: string;
    /**
     * Gets or Sets Geboortedatum
     */
    geboortedatum?: Date;
    /**
     * Gets or Sets Verblijfsadres
     */
    verblijfsadres?: BrpVerblijfsadres;
    /**
     * Gets or Sets Adresbuitenland
     */
    adresbuitenland?: BrpAdresbuitenland;
}
