/**
 * NPS op RaadpleegIngeschrevenPersoonNAW
 * NPS op RaadpleegIngeschrevenPersoonNAW (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * 
 */
export interface BrpPersoonPeriodeGeldigheid {
    /**
     * Gets or Sets Van
     */
    van?: Date;
    /**
     * Gets or Sets TotEnMet
     */
    totEnMet?: Date;
}
