/**
 * NPS op RaadpleegIngeschrevenPersoonNAW
 * NPS op RaadpleegIngeschrevenPersoonNAW (ASP.NET Core 2.0)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BrpPersoonPeriodeGeldigheid } from './brpPersoonPeriodeGeldigheid';


/**
 * 
 */
export interface BrpVerblijfsadres {
    /**
     * Gets or Sets PeriodeGeldigheid
     */
    periodeGeldigheid?: BrpPersoonPeriodeGeldigheid;
    /**
     * Gets or Sets IdentificatieNummerAanduiding
     */
    identificatieNummerAanduiding?: number;
    /**
     * Gets or Sets Postcode
     */
    postcode?: string;
    /**
     * Gets or Sets Huisnummer
     */
    huisnummer?: number;
    /**
     * Gets or Sets Huisletter
     */
    huisletter?: string;
    /**
     * Gets or Sets Huisnummertoevoeging
     */
    huisnummertoevoeging?: string;
    /**
     * Gets or Sets Locatiebeschrijving
     */
    locatiebeschrijving?: string;
    /**
     * Gets or Sets NaamOpenbareRuimte
     */
    naamOpenbareRuimte?: string;
    /**
     * Gets or Sets Woonplaatsnaam
     */
    woonplaatsnaam?: string;
    /**
     * Gets or Sets WoonplaatsIdentificatie
     */
    woonplaatsIdentificatie?: string;
    /**
     * Gets or Sets straatnaam
     */
    straatnaam?: string;
}
